[workspace]
authors = ["Oliver Batchelor <oliver.batchelor@canterbury.ac.nz>"]
channels = ["conda-forge"]
name = "d-fine-seg"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.1"
libc = { family = "glibc", version = "2.34" }


[pypi-dependencies]
d-fine-seg = { path = ".", editable = true }
build = "*"

[tasks]

[dependencies]
python = "==3.12"
pytorch-gpu = ">=2.7.1,<3"
cuda = "==12.9"
